language: node_js
node_js: 5.0

env:
    - secure: "mRXEvF/DzvEzO6RldpYi7ebqOfT76ygEE+hFhh/+jtz3glsx3/quJJXmeqN8ZVEy3rZZR58H4xdWBq2G5DzNoxXtuZc7OpufvtFo62qmwRzvs5rAvkvq/W0h8ymp/Occoy0jhgxbRfwC9pqRyFy7enoDc7kpCbI57DffncxXJyzI2dGZ6KmzvuWdOJMT8J7EQYgSBEdDlbOxn684JL7vbJv5ksixPynHrYxGNC2bujdA+Hkk3whOmns4bW7N/73lFAJ+3Kh0OSuR03Ze1TXFzjD1jb8UghRLQF3U9+GslNXZias/a0N+NXyJXmWbdaBJrSaITdk4/LU7J1ZIPycQBa3PY26oTobeb+WtJN9VX4fb+DiYo+g011b151d+29sIy/KwJTT+kCIXGUVsc70hJeVRt70J/YYAHX2G+R5pVuMQwU4sM2x16350d3yh4Wony48gSGvLTZ4V2kdA02eJijSp89tsu01B1A5ulPE2C7vrIPVn3ed9D9Tk2zZV9dQvSfVafocT0uXgkvIfDKXH1N6kSqskq53fLyOnXzOS/GH5BdPRT7WMdiXKGnObI0+wdem04jertPydtmL1SoQBfmzaDzMujEjkPqUr0K5wFvbMmGW70ZcVKoRPdjJJdV2iy/wkVvHp8tCU3hqP0X6BlzN2u7XaJ5TAIprMq3/NAkc="

before_install: npm install -g npm

before_script: npm install -g gulp
script: gulp

after_success:
    - git config --global user.name "travisvanpeerdevelopment"
    - git config --global user.email "travis@vanpeerdevelopment.be"
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${DEPLOY_TOKEN}:@github.com" > .git/credentials
    - gulp deploy
