language: node_js
node_js: 5.3

env:
    global:
        - secure: "dvws+Bs3DCSEHhZoAUlfoHnICmvgBBlN+t7FcWM58ZveOHSzWovrZ6yHUbtxM3XR73pxLXPcrzn6+M0NCwZaVDJ93/qhL8HCGNkm6tfnlpGK/FSqz15PUjF+hWdsofUhWnKUGTczDjc0o9f9lBEt9tEm6tQIxhtAm6D8lEjB6lnu9kJqicttp2ZpyXW/r475p+76/RYNuVYRTIsfg++JM6rrvZBg/VckLm4/hT6c83HZEiH+KC69OS+D4p/xT2CrnWgnPenF8yek8vYaOGAXCAH245vpIAWF5GXZ/uoAXaWBXEJ+MXUvAta13Y7FxcS4JO3U9yVOs4ybdEHe9vJq0WdCYEwzcraK23M3rZZ9q0E0gYqUQq66UMJXacqRTR+8Bs1SZH4XR0N+gr9fwGbxYhckq+reP7VDjxiKniNYEM/dGW3fz9dToSlFjcYmi1QaVE61753oV8Ri/nwi6wm1VGj7/x8i2Cb347VOpGvGBvMBWvUn+ZzsbnIP9dQspY39TNV5Uj6nsPezHKHv4w4NgVoOVe75s/kengwsK82mgG6apX5kjJHKMGO9yE8GC7ucEDdYuCnFzlWL/UQiMSfR6TZEUz0Lh0a1A5SCkhM0xfNg0xdz0RloNc3ppmTutKvPD8Y7gkk2za7fxAXHfG5Sv+RzFNkGm5Wfyouuwagta4w="
        - SAUCE_USERNAME=vanpeerdevelopment
        - secure: "QzjB3P2J8i53VCTbpRU7qUsUrLVxQKbIQvu0QI2d/9LYI+nMtJOX6SvKxdSEOjfp9URMabaM4/dexq/HXQf6kWeSvaNpEe/Oww8tzooBssNiIymIv8/UXm6JUspKxd/pkHhIKMQ9F+k38f9C51oh7LC1FXEbe1tJ0ytNqnW/gmkKi1zM+KSr5ljhQXopxCFpai4v+c+nhmb+Dm5+LOKNkoAd4uGsZaJ8iioIvdXeGJ5z+ALm4HQ3flN2UZ/t1nWrBfoxDwzLD96aA8eGzKtZq7gvVlcTViSz7c7J0Dc/Jw+RgtIUGkzd4YUDHMLoRPEOrROUJUYo8SGi5oJc+3ChJ45fF1UnJLGAwRxlZgnszv7O4N2WuwTtXTIWTSQMlTboduvEx+7p3YW18Is0Ysx5cQzhKoCYJPnHRaZWbP6/xt0K7ZwTTKQBZbUs3Akgb3IyEi7L7LIR019fYSbLNsro1JU/2bzRdjSXZYhqOHY4/CZw3OjRytutEapkpJUrX2/K2NgtK1PbKHVMR81zxHpS41tQEdWm6174RqCN/4T/6/Bvt0vO/6jcLPvaDLQoHEk4RCI7yAlfwgRlUqfMTXPjyrmnLK4Ix+vz3QaWlqsT1oPkHobnNWfrW1A85BykxPun2XUsTMFEOo7uJaqwTdcOrSfuObXnOwy0zPoktySqySU="

addons:
    sauce_connect: true

before_install:
    - npm install -g npm
    - npm install -g bower
install:
    - npm install
    - bower install

before_script:
    - npm install -g gulp
script: gulp

after_success:
    - git config --global user.name "travisvanpeerdevelopment"
    - git config --global user.email "travis@vanpeerdevelopment.be"
    - git config --global credential.helper "store --file=${TRAVIS_BUILD_DIR}/.git-credentials"
    - echo "https://travisvanpeerdevelopment:${DEPLOY_TOKEN}@github.com" > ${TRAVIS_BUILD_DIR}/.git-credentials
    - gulp deploy
