language: node_js
node_js: 5.0

env:
    - secure: "YmUUZ+9Td5E0LlrwxFCDWNWHNkiZwXLckVMI2mtyPxUwKQh7mbAztZFNbsslQMWofoVvACU5rBHiwVzJaU7DK+SWr/0aHxm2iABEjgTzDMxR0BouGHzVlDGjhLR+YfRfytHi/CYunQ5QWswPIEX5AZZ3zYN3DZnH61if3F9G5gYJOKov3HXE56QTCCUnmIhti+aRLxlHgUQErBFErUOxrwO2D9s74Lfa6AJaOs/NUSmkcwHfBhdVxrYFAt9B/tm+b2SEO4ZL/WhQWYYPCITvLaIufoWJovDat9MYN+RLj3u3SDRugHtHS5jLYRU6dDGowsHBUZkpxjkpPCv4hDOVcrgpga2ud2de2wjNU5wvSy/92DNaJnqtdYDxm+2HY6WLxWjByAJ6RoQyHXzyQupSQgOiePKgOIWiDUOWrzQTZGq9kBhcrWUS2HqtlfgUtT4gC0mpzUhSpBg/4U5RMI1w8Z3J8UC9DDSUoe02/Us1oHjF15OJbH4eekrVGO2ug5s4t3nvD9Sdft2VMdqrXPKzKpwuoyCxrUZmwX5FUw6HyvUgz+MNxxE+lnFCRBeMohK218HIljXYioOm6ynkuBTYZuqI2YK611t0awYS/HC51BbvUIBX2/Ta8gEvbFm+BOE9xL/afwDXUXAGCOrnfBGFRoMlKo7TsI4pSQDb+briS4I="

before_install: npm install -g npm

before_script: npm install -g gulp
script: gulp

after_success:
    - git config --global user.name "travisvanpeerdevelopment"
    - git config --global user.email "travis@vanpeerdevelopment.be"
    - git config --global credential.helper "store --file=~/.git-credentials"
    - echo "https://travisvanpeerdevelopment:${PASSWORD}@github.com" > ~/.git-credentials
    - gulp deploy
